var c_type=[
    
    {
		"role":"filler",
		"task":[
			{
				"task_id":0,
				"num":0,
				"equipment":[CARRY,CARRY,CARRY,MOVE],
			},		
		],
	},
	{	
		"role":"carryer",
		"task":[
			{
				"task_id":0,
				"num":0,
				"equipment":[CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,MOVE],
			},
			{
				"task_id":1,
				"num":0,
				"equipment":[CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE],
			},
		],	
	},
	
	{
		"role":"claim",
		"task":[
			{
				"task_id":0,
				"num":0,
				"equipment":[CLAIM,CLAIM,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE],
			},		
		],
	},
    {	
		"role":"army",
		"task":[
			{
				"task_id":0,
				"num":0,
				"equipment":[TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,ATTACK,ATTACK,ATTACK,ATTACK,ATTACK,ATTACK,WORK,WORK],
			},
			{
				"task_id":1,
				"num":0,
				"equipment":[HEAL,HEAL,HEAL,HEAL,MOVE,MOVE,MOVE,MOVE],
			},
			{
				"task_id":2,
				"num":0,
				"equipment":[TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,WORK,WORK,WORK,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE],
			},
			
		],	
	},
    
    
	
	{
		"role":"worker",
		"task":[
			{
				"task_id":0,
				"num":0,
				"equipment":[WORK,WORK,WORK,WORK,WORK,CARRY,CARRY,CARRY,CARRY,MOVE,MOVE],
			},
			{
				"task_id":1,
				"num":0,
				"equipment":[WORK,WORK,WORK,WORK,WORK,CARRY,CARRY,CARRY,CARRY,MOVE,MOVE],
			},
			{
				"task_id":2,
				"num":0,
				"equipment":[WORK,WORK,WORK,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE],
			},
			{
				"task_id":3,
				"num":0,
				"equipment":[WORK,WORK,WORK,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE],
			},
			{
				"task_id":4,
				"num":0,
				"equipment":[WORK,WORK,WORK,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE],
			},
		],
	},
	
	{
		"role":"settlement",
		"task":[
			
			{
				"task_id":0,
				"num":0,
				"equipment":[WORK,WORK,WORK,WORK,WORK,WORK,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE],
			},
			{
				"task_id":1,
				"num":0,
				"equipment":[WORK,WORK,WORK,WORK,WORK,WORK,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE],
			},
			{
				"task_id":2,
				"num":0,
				"equipment":[WORK,WORK,WORK,WORK,WORK,WORK,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE],
			},
			{
				"task_id":3,
				"num":0,
				"equipment":[WORK,WORK,WORK,WORK,WORK,WORK,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE],
			},
		],
	},
	
	{
		"role":"extractor",
		"task":[
			{
				"task_id":0,
				"num":0,
				"equipment":[WORK,WORK,WORK,WORK,WORK,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE],
			},	
		],
	},
		
	{
		"role":"builder",
		"task":[
			{
				"task_id":0,
				"num":0,
				"equipment":[WORK,WORK,WORK,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE],
			},	
		],
	},
	{	
		"role":"repairer",
		"task":[
			{
				"task_id":0,
				"num":0,
				"equipment":[WORK,WORK,WORK,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE],
			},
		],
	},
	
	{	
		"role":"updater",
		"task":[
			{
				"task_id":0,
				"num":0,
				"equipment":[WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE],
			},	
		],	
	},
	
]
module.exports = c_type;